name: huduma
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.0.1
  json_annotation: ^4.0.1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^0.14.2
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
