name: huduma
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.0.1
  json_annotation: ^4.0.1
  moor: ^4.3.2
  path: ^1.8.0
  path_provider: ^2.0.2
  sqlite3_flutter_libs: ^0.5.0
  provider: 

dev_dependencies:
  moor_generator: ^4.3.1
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
